In [138]:
import numpy as np

# dimensiones de la matriz A -> (4,4) , (3,2) , detecta Erro (5,7)
row_arr_A, col_arr_A = 3, 2 #3, 2 

# dimensiones de la matriz B -> (4,4) , (2,3) , detecta Erro (6,5)
row_arr_B, col_arr_B = 2, 3 #6, 5  

In [139]:
limit_random = 10

arr_A = np.random.randint(limit_random, size=(row_arr_A, col_arr_A))

arr_B = np.random.randint(limit_random, size=(row_arr_B, col_arr_B))

In [140]:
arr_A

array([[6, 7],
       [1, 3],
       [1, 5]])

In [141]:
arr_B

array([[6, 9, 1],
       [2, 5, 8]])

### Implementación de la Multiplicación de Matrices 

In [142]:
# Si no valen las multiplicaciones que tiene por defecto el array de 1 sola dimensión numpy
def mult_array(array_A, array_B):
    sumValue = 0
    len_A = len(array_A)
    for i in range(len_A):
        sumValue += array_A[i] * array_B[i]
    return sumValue

In [143]:
def mult_matrix(matrix_A: np.ndarray, matrix_B: np.ndarray):
    row_A, col_A = matrix_A.shape
    row_B, col_B = matrix_B.shape
    matrix_Result = []

    if col_A == row_B:
        matrix_B = matrix_B.transpose()
        for i in range(row_A):
            new_row = []
            for j in range(col_B):
                # item = mult_array(matrix_A[i], matrix_B[j])
                item = (matrix_A[i] * matrix_B[j]).sum()
                new_row.append(item)
            matrix_Result.append(new_row)
        return np.array(matrix_Result)
    else:
        print(
            "La segunda dimensión de la primera matriz debe ser igual a la primera dimensión de la segunda matriz"
        )

In [144]:
mult_matrix(arr_A, arr_B)

array([[50, 89, 62],
       [12, 24, 25],
       [16, 34, 41]])