In [3]:
import numpy as np

# dimensiones de la matriz A
row_arr_A = 4
col_arr_A = 4

# dimensiones de la matriz B
row_arr_B = 4
col_arr_B = 4

In [7]:
limit_random = 10

arr_A = np.random.randint(limit_random, size=(row_arr_A, col_arr_A))

arr_B = np.random.randint(limit_random, size=(row_arr_A, col_arr_B))

In [8]:
arr_A

array([[1, 9, 4, 0],
       [0, 5, 2, 0],
       [2, 5, 8, 5],
       [9, 5, 8, 8]])

In [9]:
arr_B

array([[8, 9, 8, 5],
       [7, 0, 9, 2],
       [9, 5, 8, 0],
       [5, 2, 1, 9]])

### Implementación de la Multiplicación de Matrices 

In [10]:
type(arr_A)

numpy.ndarray

In [24]:
a = [1,2,3]
b = [3,5,6]
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [35]:
def mult_array(array_A, array_B):
    #     for a, b in zip(array_A, array_B):
    value = 0
    len_A = len(arr_A)
    for i in range(len_A):
        value +=value + (array_A[i] * array_B[i])
    return value

In [47]:
print(arr_B.transpose())

[[8 7 9 5]
 [9 0 5 2]
 [8 9 8 1]
 [5 2 0 9]]


In [56]:
def mult_matrix(matrix_A: np.ndarray, matrix_B: np.ndarray):
    row_A, col_A = matrix_A.shape
    row_B, col_B = matrix_B.shape
    print(row_A)

    if col_A == row_A:
        for i in range(row_A):
#             print(matrix_A[i])
            new_row = []
            for j in range(col_B):
#                 print(matrix_B.transpose()[j])
                item = mult_array(matrix_A[i],matrix_B.transpose()[j])
                new_row.append(item)
print(new_row)

    else:
        print(
            "La segunda dimensión de la primera matrix debe ser igual a la primera dimensión de la segunda matrix"
        )

In [57]:
mult_matrix(arr_A,arr_B)

4
[1 9 4 0]
[8 7 9 5]
[9 0 5 2]
[8 9 8 1]
[5 2 0 9]
[0 5 2 0]
[8 7 9 5]
[9 0 5 2]
[8 9 8 1]
[5 2 0 9]
[2 5 8 5]
[8 7 9 5]
[9 0 5 2]
[8 9 8 1]
[5 2 0 9]
[9 5 8 8]
[8 7 9 5]
[9 0 5 2]
[8 9 8 1]
[5 2 0 9]
