# Calculadora de matrices con Numpy

In [27]:
import numpy as np
# Trabajo de hacer calculadoras de matrices 
# con las operaciones sumas, restar, multiplicar, imprimir la diagonal(las 2 diagonales), determinante

### Funciones de las operaciones 
*Multiplicación: Implementación sin la sobrecarga de numpy*

In [28]:
def suma(matrix_A: np.ndarray, matrix_B: np.ndarray):
    if matrix_A.shape == matrix_B.shape:
        return matrix_A + matrix_B
    print("Matrices con diferentes dimensiones")
    return None

def restar(matrix_A: np.ndarray, matrix_B: np.ndarray):
    if matrix_A.shape == matrix_B.shape:
        return matrix_A - matrix_B
    print("Matrices con diferentes dimensiones")
    return None
    
def mult_matrix(matrix_A: np.ndarray, matrix_B: np.ndarray):
    row_A, col_A = matrix_A.shape
    row_B, col_B = matrix_B.shape
    matrix_Result = []

    if col_A == row_B:
        matrix_B = matrix_B.transpose()
        for i in range(row_A):
            new_row = []
            for j in range(col_B):
                # item = mult_array(matrix_A[i], matrix_B[j])
                item = (matrix_A[i] * matrix_B[j]).sum()
                new_row.append(item)
            matrix_Result.append(new_row)
        return np.array(matrix_Result)
    else:
        print(
            "La segunda dimensión de la primera matriz debe ser igual a la primera dimensión de la segunda matriz"
        )
        
def diagonal(matrix ,diagonal_main = True):
    if diagonal_main:
        main_diagonal = matrix.diagonal()
        return  main_diagonal
    else:
        fila,columna = matrix.shape
        diagonal_secondary = []
        for i in range(fila):
            diagonal_secondary.append(matrix[i][(columna-1)-i])
        return diagonal_secondary

def determinate(matrix):
    return np.linalg.det(matrix)
    


In [29]:
def input_matrix(orden):
    row = int(input("Ingrese el numero de filas de la " + orden + " matrix:"))
    col = int(input("Ingrese el numero de columnas de la " + orden + " matrix:"))

    # Initialize matrix
    matrix = []
    print("Ingrese:")

    for i in range(row):
        a = []
        for j in range(col):
            a.append(int(input()))
        matrix.append(a)

    return matrix


def calculadora():
    print("-" * 10, "Bienvenido a la calculadora de matrices", "-" * 10)
    keep = True
    operation_need_two_matrix = ["1", "2", "3"]
    operation_need_one_matrix = ["4", "5"]
    while keep:
        print("-" * 5, "Operaciones disponibles", "-" * 5, "\n\n")

        print("Suma:1")
        print("Resta:2")
        print("Multiplicación:3")
        print("Diagonal:4")
        print("Determinante:5")
        print("Salir:6", "\n\n")

        operation = input(
            "Seleccione la operación escribiendo el numero correspondiente:"
        )
        print("\n\n")
        matrix_1 = None
        matrix_2 = None
        result = None

        # --------creación de las matrices-------
        if operation in operation_need_two_matrix:
            matrix_1 = np.array(input_matrix("primera"))
            matrix_2 = np.array(input_matrix("segunda"))

            print("Primera Matrix")
            print(matrix_1)

            print("Segunda Matrix")
            print(matrix_2)

        elif operation in operation_need_one_matrix:
            matrix_1 = np.array(input_matrix(""))
            print("La matrix ingresada")
            print(matrix_1)
        elif operation == "6":
            print("Saliendo de la calculadora...")
            keep = False
        else:
            print("Operación no valida")

        # -------llamar a las operaciones------
        if operation == "1":
            result = suma(matrix_1, matrix_2)
            if result is not None:
                print("La suma resultante es")
                print(result)
        elif operation == "2":
            result = restar(matrix_1, matrix_2)
            if result is not None:
                print("La resta resultante es")
                print(result)
        elif operation == "3":
            result = mult_matrix(matrix_1, matrix_2)
            if result is not None:
                print("El producto resultante es")
                print(result)
        elif operation == "4":
            print(
                "A continuación se le pedira escoger 2 de las diagonales que le permite extraer",
                "\n\n",
            )
            print("Diagonal principal:1")
            print("Diagonal secundaria:2", "\n\n")
            opcion = input("Seleccione el tipo de diagonal:")
            if opcion == "1":
                result = diagonal(matrix_1)
                if result is not None:
                    print("El diagonal principal es")
                    print(result)
            elif opcion == "2":
                result = diagonal(matrix_1, False)
                if result is not None:
                    print("La diagonal secundaria es ")
                    print(result)
            else:
                print("operación no valida")
        elif operation == "5":
            result = determinate(matrix_1)
            if result is not None:
                print("La determinante de la matrix es ")
                print(result)

### Interacción con el usuario: 

In [30]:
calculadora()

---------- Bienvenido a la calculadora de matrices ----------
----- Operaciones disponibles ----- 


Suma:1
Resta:2
Multiplicación:3
Diagonal:4
Determinante:5
Salir:6 


Seleccione la operación escribiendo el numero correspondiente:1



Ingrese el numero de filas de la primera matrix:2
Ingrese el numero de columnas de la primera matrix2
Ingrese:
1
2
3
4
Ingrese el numero de filas de la segunda matrix:2
Ingrese el numero de columnas de la segunda matrix2
Ingrese:
5
6
7
8
Primera Matrix
[[1 2]
 [3 4]]
Segunda Matrix
[[5 6]
 [7 8]]
La suma resultante es
[[ 6  8]
 [10 12]]
----- Operaciones disponibles ----- 


Suma:1
Resta:2
Multiplicación:3
Diagonal:4
Determinante:5
Salir:6 


Seleccione la operación escribiendo el numero correspondiente:2



Ingrese el numero de filas de la primera matrix:2
Ingrese el numero de columnas de la primera matrix2
Ingrese:
1
2
3
4
Ingrese el numero de filas de la segunda matrix:2
Ingrese el numero de columnas de la segunda matrix2
Ingrese:
5
6
7
8
Primera Mat