In [1]:
import numpy as np
# shift + tab + tab ver parametros

In [4]:
matrix = np.zeros((4,4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
limit_random = 20
matrix = np.random.randint(low = 1,high = limit_random, size=(7, 10))
matrix

array([[ 1,  5,  1, 10, 10,  4,  3, 13, 11, 11],
       [ 4, 14,  5, 13, 14, 12,  2, 13,  4,  4],
       [14,  8, 19, 19, 19, 10,  9,  1,  7, 12],
       [16, 18,  2,  1, 11, 17,  1, 14, 11, 17],
       [14, 11, 13,  3, 14,  4, 16,  2,  8, 16],
       [ 8, 13, 14, 10,  3,  2, 13,  5,  8, 12],
       [ 7, 13,  3, 10,  1, 12, 19,  3, 10,  5]])

In [8]:
matrix = np.ones((4,4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# calculadoras de matrices : sumas, restar, multiplicar, imprimir la diagonal(las 2 diagonales), sacar determinante

def suma(matrix_A: np.ndarray, matrix_B: np.ndarray):
    return matrix_A + matrix_B
        

def restar(matrix_A: np.ndarray, matrix_B: np.ndarray):
    return matrix_A - matrix_B
    
def mult_matrix(matrix_A: np.ndarray, matrix_B: np.ndarray):
    row_A, col_A = matrix_A.shape
    row_B, col_B = matrix_B.shape
    matrix_Result = []

    if col_A == row_B:
        matrix_B = matrix_B.transpose()
        for i in range(row_A):
            new_row = []
            for j in range(col_B):
                # item = mult_array(matrix_A[i], matrix_B[j])
                item = (matrix_A[i] * matrix_B[j]).sum()
                new_row.append(item)
            matrix_Result.append(new_row)
        return np.array(matrix_Result)
    else:
        print(
            "La segunda dimensión de la primera matriz debe ser igual a la primera dimensión de la segunda matriz"
        )
        
def diagonal(matrix ,diagonal_main = True):
    if diagonal_main:
        main_diagonal = matrix.diagonal()
        return  main_diagonal
    else:
        fila,columna = matrix.shape
        diagonal_secondary = []
        for i in range(fila):
            diagonal_secondary.append(matrix[i][(columna-1)-i])
        return diagonal_secondary

def determinate(matrix):
    return np.linalg.det(matrix)
    


In [ ]:
def input_matrix(orden):
    row = int(input("Ingrese el numero de filas de la " + orden+ " matrix:"))
    col = int(input("Ingrese el numero de columnas de la "+orden +  " matrix"))
  
    # Initialize matrix
    matrix = []
    print("Ingrese:")
  
    for i in range(row):          
        a =[]
        for j in range(col):      
             a.append(int(input()))
        matrix.append(a)
    
    return matrix

def calculadora():
    m1 = np.array(input_matrix("primera"))
#     m2 = np.array(input_matrix("segunda"))
    
    print(m1)
    
#     print("Suma:1")
#     print("Resta:2")
#     print("Multiplicación:3")
#     print("Diagonal:4")
#     print("Determinante:5")
    
#     operation = input("Seleccione la operación:")
    
#     if operation == "1":
#         result = suma(m1,m2)
#         print(result)
#     elif operation=="2":
#         result =restar(m1,m2)
#         print(result)
#     elif operation=="3":
#         result = mult_matrix(m1,m2)
#         print(result)
#     elif operation=="4":
#         print("Diagonal principal:1")
#         print("Diagonal secundaria:2")
#         opcion = input("Seleccione la opción")
#         if opcion=="1":
#             print("Diagonal de la Matrix 1 = ",diagonal(m1))
#             print("Diagonal de la Matrix 2 = ",diagonal(m2))
#         elif opcion=="2":
#             print("Diagonal de la Matrix 1 = ",diagonal(m1,False))
#             print("Diagonal de la Matrix 2 = ",diagonal(m2,False))
#         else:
#             print("operación no valida")
#     elif determinate=="5":
#         determinate("Determinante de la matrix 1 = ",m1)
#         determinate("Determinante de la matrix 2 = ",m2)
#     else:
#         print("Operación no valida")

In [ ]:
calculadora()


### Probando metodos: 

In [43]:
new_matrix_1 = np.random.randint(low = 1,high = limit_random, size=(3, 3))
new_matrix_2 = np.random.randint(low = 1,high = limit_random, size=(3, 3))

In [53]:
new_matrix_1

array([[11,  8,  8],
       [12,  1, 14],
       [ 9,  2,  6]])

In [54]:
new_matrix_2

array([[ 1,  5, 13],
       [16,  6,  1],
       [11, 17,  1]])

In [44]:
suma(new_matrix_1,new_matrix_2)

array([[12, 13, 21],
       [28,  7, 15],
       [20, 19,  7]])

In [45]:
restar(new_matrix_1,new_matrix_2)

array([[ 10,   3,  -5],
       [ -4,  -5,  13],
       [ -2, -15,   5]])

In [46]:
mult_matrix(new_matrix_1,new_matrix_2)

array([[227, 239, 159],
       [182, 304, 171],
       [107, 159, 125]])

In [50]:
diagonal(new_matrix_1)

array([11,  1,  6])

In [51]:
diagonal(new_matrix_1,False)

[8, 1, 9]

In [52]:
determinate(new_matrix_1)

310.00000000000006

### Interacción con usuario