In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lecturas de Datos

In [14]:
# Link del dataset: https://www.kaggle.com/datasets/CooperUnion/cardataset
# El dataset sobre carros
df = pd.read_csv("data/data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [15]:
features = ["Year","Engine Cylinders","Engine HP"]
# features = ["Engine Cylinders","Engine HP"]
# features = ["Year","Engine Cylinders","Engine HP","Vehicle Size"]
label_y = "MSRP"

In [16]:
n_features = len(features)

In [17]:
df = df[features+[label_y]]
df

Year  Engine Cylinders  Engine HP   MSRP
0      2011               6.0      335.0  46135
1      2011               6.0      300.0  40650
2      2011               6.0      300.0  36350
3      2011               6.0      230.0  29450
4      2011               6.0      230.0  34500
...     ...               ...        ...    ...
11909  2012               6.0      300.0  46120
11910  2012               6.0      300.0  56670
11911  2012               6.0      300.0  50620
11912  2013               6.0      300.0  50920
11913  2006               6.0      221.0  28995

[11914 rows x 4 columns]

In [18]:
df.isnull().sum()

Year                 0
Engine Cylinders    30
Engine HP           69
MSRP                 0
dtype: int64

In [19]:
# Eliminar registros con valor "nan"
df = df.dropna()
df.isnull().sum()

Year                0
Engine Cylinders    0
Engine HP           0
MSRP                0
dtype: int64

In [20]:
df = df[:100]

In [23]:
from sklearn import preprocessing
# scaler.mean_
# to std : estimador sesgado 
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler

In [30]:
scaler = preprocessing.StandardScaler(with_std=True,with_mean=True).fit(df)
scaler_data = scaler.transform(df)
df_scaler = pd.DataFrame(scaler_data,columns=df.columns)

In [31]:
df_scaler

Year  Engine Cylinders  Engine HP      MSRP
0   0.412197          0.971398   1.900822  1.457578
1   0.412197          0.971398   1.361166  1.134345
2   0.412197          0.971398   1.361166  0.880945
3   0.412197          0.971398   0.281854  0.474326
4   0.412197          0.971398   0.281854  0.771924
..       ...               ...        ...       ...
95 -0.800146         -1.095406  -1.105832 -1.139010
96 -0.986660         -1.095406  -0.874551 -1.042365
97 -0.986660         -1.095406  -0.874551 -1.053738
98 -0.893403         -1.095406  -0.874551 -1.030755
99 -0.893403         -1.095406  -0.874551 -1.014726

[100 rows x 4 columns]

In [34]:
x_scaler = df_scaler[features]
y_scaler = df_scaler[label_y]

In [35]:
print(x_scaler[:5])
print(y_scaler[:5])

       Year  Engine Cylinders  Engine HP
0  0.412197          0.971398   1.900822
1  0.412197          0.971398   1.361166
2  0.412197          0.971398   1.361166
3  0.412197          0.971398   0.281854
4  0.412197          0.971398   0.281854
0    1.457578
1    1.134345
2    0.880945
3    0.474326
4    0.771924
Name: MSRP, dtype: float64


# Probado hasta aqui

In [166]:
x_whole= x_whole.to_numpy()

In [192]:
x_whole[:5]

array([[1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 3.350e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 2.300e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 2.300e+02]])

In [168]:
x_whole.shape

(100, 3)

In [191]:
n_ones = np.ones([len(x_whole), 1])
x_whole = np.concatenate((n_ones, x_whole), axis=1)
x_whole[:5]

array([[1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 3.350e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 2.300e+02],
       [1.000e+00, 1.000e+00, 2.011e+03, 6.000e+00, 2.300e+02]])

Definiendo la Función de Costo y la función de Hipótesis $H_{\theta}(x)$
- Función de Costo:
$$
J(\theta)=J(\theta_{0},\theta_{1},\dots,\theta_{n})\\
J(\theta) = \frac{1}{2m}\sum_{i=0}^{m}( h_{\theta}(x^{(i)})-y^{(i)})^{2}
$$
- Hipótesis
$$
h_{\theta}(x) = \theta_{0} + \theta_{1}x_{1} + \dots + \theta_{n}x_{n} = \theta^{T}x
$$

In [170]:
def predict(thetas, x_data):
    return np.dot(x_data, thetas)

In [171]:
def fun_cost(x_data, y_result, thetas):
    cost = 0
    # m
    len_data_x = x_data.shape[0]
    cost = 0

    predict_error = predict(thetas, x_data) - y_result
    square_predict_error = np.power(predict_error, 2)

    sumatoria_error_cuadratico = np.sum(square_predict_error)
    cost = 1.0 / (2 * len_data_x) * sumatoria_error_cuadratico
    return cost

In [172]:
thetas = np.zeros(n_features + 1)
thetas = thetas.reshape(n + 1, 1)
thetas

array([[0.],
       [0.],
       [0.],
       [0.]])

In [173]:
y_whole = y_whole.to_numpy()
y_whole

array([46135, 40650, 36350, 29450, 34500, 31200, 44100, 39300, 36900,
       37200, 39600, 31500, 44400, 37200, 31500, 48250, 43550,  2000,
        2000,  2000,  2000,  2000,  2000,  2000,  2000,  2000,  2000,
        2000,  2000,  2000,  2000,  2000, 27495, 24995, 28195,  2000,
        2000,  2000,  2000,  2000,  2000, 32850, 38650, 48750, 34850,
       40650, 44150, 32850, 46150, 50750, 46450, 49050, 51050, 44450,
       38950, 33150, 35150, 40950,  2000,  2000,  2000,  2000,  2000,
        2000, 25170, 23950, 29370, 21995, 26625, 30825, 21995, 27795,
       31785, 29905, 22490, 27570, 25690, 24490, 29905, 31785, 26685,
       22490, 25690, 30900, 27795, 21995, 24490,  2000,  2000,  2000,
        2000,  2000,  2000,  2000,  2000,  2073,  3713,  3520,  3910,
        4182], dtype=int64)

In [174]:
y_whole.flatten()

array([46135, 40650, 36350, 29450, 34500, 31200, 44100, 39300, 36900,
       37200, 39600, 31500, 44400, 37200, 31500, 48250, 43550,  2000,
        2000,  2000,  2000,  2000,  2000,  2000,  2000,  2000,  2000,
        2000,  2000,  2000,  2000,  2000, 27495, 24995, 28195,  2000,
        2000,  2000,  2000,  2000,  2000, 32850, 38650, 48750, 34850,
       40650, 44150, 32850, 46150, 50750, 46450, 49050, 51050, 44450,
       38950, 33150, 35150, 40950,  2000,  2000,  2000,  2000,  2000,
        2000, 25170, 23950, 29370, 21995, 26625, 30825, 21995, 27795,
       31785, 29905, 22490, 27570, 25690, 24490, 29905, 31785, 26685,
       22490, 25690, 30900, 27795, 21995, 24490,  2000,  2000,  2000,
        2000,  2000,  2000,  2000,  2000,  2073,  3713,  3520,  3910,
        4182], dtype=int64)

In [175]:
y_whole.shape

(100,)

In [176]:
x_whole.shape

(100, 4)

In [185]:
x_whole[:5]

array([[1.000e+00, 2.011e+03, 6.000e+00, 3.350e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 2.300e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 2.300e+02]])

In [178]:
thetas.shape

(4, 1)

In [179]:
fun_cost(x_whole,y_whole,thetas)

37297979261.0

In [186]:
predict(thetas, x_whole)[:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [181]:
thetas.flatten()

array([0., 0., 0., 0.])

<b>Gradiente</b>
\begin{equation}
\frac{\partial J(\theta)}{\partial \theta_j} = 1/m\sum_{i=1}^{m}(h(\theta^{(i)} - y^{(i)}).X_j^{(i)}
\end{equation}

<b>Gradientes</b>
\begin{equation}
\theta_0: = \theta_0 -\alpha . (1/m .\sum_{i=1}^{m}(h(\theta^{(i)} - y^{(i)}).X_0^{(i)})
\end{equation}
\begin{equation}
\theta_1: = \theta_1 -\alpha . (1/m .\sum_{i=1}^{m}(h(\theta^{(i)} - y^{(i)}).X_1^{(i)})
\end{equation}
\begin{equation}
\theta_2: = \theta_2 -\alpha . (1/m .\sum_{i=1}^{m}(h(\theta^{(i)} - y^{(i)}).X_2^{(i)})
\end{equation}

\begin{equation}
\theta_j: = \theta_j -\alpha . (1/m .\sum_{i=1}^{m}(h(\theta^{(i)} - y^{(i)}).X_0^{(i)})
\end{equation}

In [189]:
# gradiente descendiente
def gradient_descent(x_data, y_data, thetas, learning_rate=0.01, iterations=100):
    m = len(y_data)
    cost_history = np.zeros(iterations)
    theta_history = np.zeros((iterations, len(thetas)))

    y_data = y_data.flatten()

    for it in range(iterations):
        # Hipotesis retornar array en una fila y no columna
        # por ello la "flatten" a la variable Thetas
        #         prediction = predict(thetas.flatten(),x_data) #8921
        prediction = predict(thetas, x_data)  # 8921

        # x_data.T -> 4, 8291
        thetas = thetas - (learning_rate * (1 / m) * (x_data.T.dot((prediction.flatten() - y_data)))).reshape(4,1)
#         print(theta_history.shape)
#         print(theta_history[0])
#         print(thetas)
        theta_history[it] = thetas.flatten()
        cost_history[it] = fun_cost(x_data, y_data, thetas)

    return thetas, cost_history, theta_history

In [190]:
theta,cost_history,theta_history = gradient_descent(x_whole,y_whole,thetas,0.01,50)

C:\Users\Admin\AppData\Local\Temp\ipykernel_6268\1282330556.py:8: RuntimeWarning: overflow encountered in power
  square_predict_error = np.power(predict_error, 2)


In [ ]:
print("Theta =",theta)
print("Final Cost = ",cost_history[-1])