In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lecturas de Datos

In [39]:
# Link del dataset: https://www.kaggle.com/datasets/CooperUnion/cardataset
# El dataset sobre carros
df = pd.read_csv("data/data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [40]:
features = ["Year","Engine Cylinders","Engine HP"]
# features = ["Engine Cylinders","Engine HP"]
# features = ["Year","Engine Cylinders","Engine HP","Vehicle Size"]
y = "MSRP"

In [41]:
n_features = len(features)

In [42]:
df = df[features+[y]]
df

Year  Engine Cylinders  Engine HP   MSRP
0      2011               6.0      335.0  46135
1      2011               6.0      300.0  40650
2      2011               6.0      300.0  36350
3      2011               6.0      230.0  29450
4      2011               6.0      230.0  34500
...     ...               ...        ...    ...
11909  2012               6.0      300.0  46120
11910  2012               6.0      300.0  56670
11911  2012               6.0      300.0  50620
11912  2013               6.0      300.0  50920
11913  2006               6.0      221.0  28995

[11914 rows x 4 columns]

In [43]:
df.isnull().sum()

Year                 0
Engine Cylinders    30
Engine HP           69
MSRP                 0
dtype: int64

In [44]:
# Eliminar registros con valor "nan"
df = df.dropna()
df.isnull().sum()

Year                0
Engine Cylinders    0
Engine HP           0
MSRP                0
dtype: int64

In [45]:
x_whole =df[features]
y_whole = df[y]

In [46]:
x_whole

Year  Engine Cylinders  Engine HP
0      2011               6.0      335.0
1      2011               6.0      300.0
2      2011               6.0      300.0
3      2011               6.0      230.0
4      2011               6.0      230.0
...     ...               ...        ...
11909  2012               6.0      300.0
11910  2012               6.0      300.0
11911  2012               6.0      300.0
11912  2013               6.0      300.0
11913  2006               6.0      221.0

[11816 rows x 3 columns]

In [47]:
x_whole= x_whole.to_numpy()

In [48]:
x_whole

array([[2011.,    6.,  335.],
       [2011.,    6.,  300.],
       [2011.,    6.,  300.],
       ...,
       [2012.,    6.,  300.],
       [2013.,    6.,  300.],
       [2006.,    6.,  221.]])

In [49]:
x_whole.shape

(11816, 3)

In [50]:
n_ones = np.ones([len(x_whole), 1])
x_whole = np.concatenate((n_ones, x_whole), axis=1)
x_whole

array([[1.000e+00, 2.011e+03, 6.000e+00, 3.350e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       ...,
       [1.000e+00, 2.012e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.013e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.006e+03, 6.000e+00, 2.210e+02]])

In [51]:
def predict(thetas, x_data):
    return np.dot(x_data, thetas)

In [52]:
def fun_cost(x_data, y_result, theta):
    cost = 0
    # m
    len_data_x = x_data.shape[0]
    cost = 0

    predict_error = predict(theta, x_data) - y_result
    square_predict_error = np.power(predict_error, 2)

    sumatoria_error_cuadratico = np.sum(square_predict_error)
    cost = 1.0 / (2 * len_data_x) * sumatoria_error_cuadratico
    return cost

In [58]:
x_whole

array([[1.000e+00, 2.011e+03, 6.000e+00, 3.350e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.011e+03, 6.000e+00, 3.000e+02],
       ...,
       [1.000e+00, 2.012e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.013e+03, 6.000e+00, 3.000e+02],
       [1.000e+00, 2.006e+03, 6.000e+00, 2.210e+02]])

In [59]:
x_whole.shape

(11816, 4)

In [57]:
n = len(features)
thetas =  np.zeros(n+1)
thetas= thetas.reshape(n+1,1)
thetas

array([[0.],
       [0.],
       [0.],
       [0.]])

In [64]:
predict(thetas,x_whole)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [66]:
thetas = thetas.flatten()

In [68]:
fun_cost(x_whole,y_whole,thetas)

2642322019.357354